# Generated by Django 4.2.2 on 2023-06-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_course_alter_user_avatar_submission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="Course",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="participant",
        ),
        migrations.DeleteModel(
            name="Assignements",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
