# Generated by Django 4.2.2 on 2023-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_course_participants_remove_submission_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="profile_pitures/def.jpg", upload_to="./Profile_images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="teacher",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
