# Generated by Django 4.2.2 on 2023-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar_alter_user_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="def.jpg", null=True, upload_to="./Profile_images/"
            ),
        ),
    ]
