# Generated by Django 4.2.2 on 2023-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="./Profile_images/def.jpg",
                null=True,
                upload_to="./Profile_images/",
            ),
        ),
    ]
