# Generated by Django 4.2.2 on 2023-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignements",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="assignements",
            name="Details",
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
