# Generated by Django 4.2.2 on 2023-06-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_submission_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="Assignement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subAssignement",
                to="core.assignements",
            ),
        ),
    ]
