# Generated by Django 4.2.2 on 2023-06-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_submission_assignement"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="Document",
            field=models.FileField(blank=True, null=True, upload_to="./submissions/"),
        ),
        migrations.AlterField(
            model_name="assignements",
            name="Documents",
            field=models.FileField(blank=True, null=True, upload_to="./documents/"),
        ),
    ]
