# Generated by Django 4.2.2 on 2023-06-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_submission_document_alter_assignements_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
