# Generated by Django 4.2.2 on 2023-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_submission_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignements",
            name="Details",
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
    ]
