# Generated by Django 4.2.2 on 2023-06-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_assignements_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="details",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
